### ISSUE TITLE
Code copy removes '#' from code comments

### ISSUE THREAD

**Issue by paul-e-allen** [CU-CommunityApps/ct-azure-openai-gpt4-chat#174]
When copying bot code snippets, `#` comment markers go missing.

For example, suppose the code generated by the bot is the following:
```
# This is a simple Python script that displays "Hello, World!" on the screen.
print("Hello, World!")
```

If you use the "copy-to-clipboard" icon next to the code snippet, the following is the actual code that is copied:
```
This is a simple Python script that displays "Hello, World!" on the screen.
print("Hello, World!")
```

When using the "copy-to-clipboard" icon next to the entire bot response, the `#` in code comments do properly get copied:
```
Certainly! Here's the "Hello, World!" Python script with comments:

# This is a simple Python script that displays "Hello, World!" on the screen.
print("Hello, World!")

```

**Comment by paul-e-allen** [comment]
There is also a similar(?) issue with `__` (double underscore).

Code that is generated:
```
# Run the script
if __name__ == '__main__':
    main()
```

Code that is copied:
```
Run the script
if name == 'main':
    main()
```

**Comment by mikesprague** [comment]
I suspect my `markdownToText` helper (https://github.com/CU-CommunityApps/ct-azure-openai-gpt4-chat/blob/5016c8d19aed654bb2b9d5f620a625a1e95dfc96/app/utils/markdownToText.ts#L40-L52) that preprocesses the string to copy may be to blame and will try to resolve sometime this week. 

Thanks for reporting!

**Comment by paul-e-allen** [comment]
Not a urgent problem. I'm very happy to fix up comments and other minor things when the bot does all the heavy lifting!

**Comment by mikesprague** [comment]
For my future reference, here's a quick example I just did:
<img width="1187" alt="Screenshot 2024-01-04 at 08 31 44" src="https://github.com/CU-CommunityApps/ct-azure-openai-gpt4-chat/assets/560705/5570dc05-12b4-480c-841f-d2bdfc86d114">

And the Python code after clicking copy button:

```python
Define a function named 'add_numbers' that takes two parameters: 'num1' and 'num2'.

def add_numbers(num1, num2):
    # Add the two numbers together and store the result in a variable called 'sum'.
    sum = num1 + num2
    # Return the result of the addition.
    return sum

Example usage of the function:

Call the 'add_numbers' function with 3 and 4 as arguments, and print the result.

print(add_numbers(3, 4))  # Output: 7
```

Interesting to note it left some `#` in there and removed the others. I suspect it's treating non-indented `#`s as heading indicators for Markdown and stripping them - if my theory is correct, that could apply to the underscores too since they are used in Markdown formatting as well.

Thanks again for reporting this, def an interesting one.
